### ISSUE TITLE
Card_Create() fails when game share filename prefixes

### ISSUE THREAD

**Issue by suloku** [devkitPro/libogc#113]
https://github.com/devkitPro/libogc/blob/bc4b778d558915aa40676e33514c4c9ba2af66b8/libogc/card.c#L2704

Example: For Paper Mario two files with the same gamecode and company can be in the same memory card: "rel" and "rel_settings"

If the file "rel_settings" is already present in the memory card when trying to restore "rel", when Card_CreateAsync parses trough the directory entries it will find "rel_setting", but since it will only compare the lenght of the file to create (in this case 3 bytes, snce we are trying to create the "rel" file), memcmp will result in zero and thus Card_CreateAsync will report a CARD_ERROR_EXIST.

Proposed solution is to memcmp the full allowed filename lenght:

else if(memcmp(entry[i].filename,filename,CARD_FILENAMELEN)==0)

**Comment by suloku** [comment]
Just noticed the same happens in CARD_CreateEntryAsync()

**Comment by WinterMute** [comment]
Fixed with https://github.com/devkitPro/libogc/commit/110eb06e3cd003e4d7f5394115ad299a7635f5ca
