### ISSUE TITLE
Ubuntu 21.04 Error: unknown type name 'BOOL'  13 | BOOL MP3Player_IsPlaying(void);

### ISSUE THREAD

**Issue by Special-Niewbie** [devkitPro/libogc#117]
Hello everyone,

i have set a new machine with Ubuntu 21.04, when I try to build my project I have got  this Error:

```
/opt/devkitpro/libogc/include/mp3player.h:13:1: error: unknown type name 'BOOL'
   13 | BOOL MP3Player_IsPlaying(void);
```

Have you any idea why it happens this. Months ago, with Linux, I don't remember that i ever face this type of error

**Comment by Special-Niewbie** [comment]
Update:

I modified the header, and it seems that the capitol letter it gives the problem with BOOL function. 

I will keep you posted on that if everything will works....

**Comment by DacoTaco** [comment]
OP never replied, and the `BOOL`in that header has been replaced with `bool`
