### ISSUE TITLE
Wrong calibration data for Wii U Pro controller

### ISSUE THREAD

**Issue by Oibaf66** [devkitPro/libogc#12]
The Wii U Pro controller does not provide calibration data therefore these data have been written in the code (classic.c)

`/* is this a wiiu pro? */
   if (len > 223 && data[223] == 0x20) {
      cc->ljs.max.x = cc->ljs.max.y = 0xFF;
      cc->ljs.min.x = cc->ljs.min.y = 0;
      cc->ljs.center.x = cc->ljs.center.y = 0x80;

      cc->rjs = cc->ljs;

      cc->type = 2;
   }`

However the min and max values (0 and 0xFF) are not correct and far from the real values.
More convenient values should be min=55 and max=197. 
Wrong calibration data lead to wrong polar coordinates values (in particular exp.classic.ljs.mag).

It would be necessary to test some Wii U Pro controllers to have more precise results on min, center and max calibration data.

See also:
http://devkitpro.org/viewtopic.php?f=7&t=8642

**Comment by Oibaf66** [comment]
After testing another Wii U Pro controller, better values are min=48 and max=208

**Comment by WinterMute** [comment]
I merged https://github.com/devkitPro/libogc/pull/14 but I don't have controllers to test with. Is there anything else that needs done for this?

**Comment by Oibaf66** [comment]
No, there is not.
I used this patch for Fbzx wii rel. 15.
I got these values submitting a test to two users:

https://gbatemp.net/threads/fbzx-wii-wii-u-pro-controller-support.455944/

**Comment by WinterMute** [comment]
Cheers, closing as fixed
