### ISSUE TITLE
ogc_card_writepage() incorrectly calculates offset after block 1024

### ISSUE THREAD

**Issue by suloku** [devkitPro/libogc#120]
ogc_card_writepage() will start over when the memory card has over 1024 blocks

```
card->cmd[1] = (card->cmd_sector_addr>>17)&0x3f;
card->cmd[2] = (card->cmd_sector_addr>>9)&0xff;
card->cmd[3] = (card->cmd_sector_addr>>7)&3;
card->cmd[4] = card->cmd_sector_addr&0x7f;
```

After address 0x800000 the results are the same as 0x0000, next block (0x802000) is equal to 0x2000 and so on.

This is correctly handled in ogc_card_readsegment() (haven't checked the values for more than 2048 0x2000 sector blocks though, not that there are bigger memory cards...)

```
card->cmd[1] = (card->cmd_sector_addr&0xFE0000)>>17;
card->cmd[2] = (card->cmd_sector_addr&0x01FE00)>>9;
card->cmd[3] = (card->cmd_sector_addr&0x000180)>>7;
card->cmd[4] = (card->cmd_sector_addr&0x00007F);
```

I haven't tested restoring single savegames to a memory card that is already filled further than 1023 blocks, but raw writing doesn't work unless ogc_card_writepage is updated to calculate offsets as ogc_card_readsegment()

This has been tested and seems to be working fine so far.

**Comment by WinterMute** [comment]
Could you submit a PR with your fix please?

**Comment by DacoTaco** [comment]
PR verified and merged
