### ISSUE TITLE
GX_SetDispCopyDst takes a `ht` argument, however it is not used in the function. 

### ISSUE THREAD

**Issue by ProfElements** [devkitPro/libogc#125]

**Comment by DacoTaco** [comment]
can you provide any more information?
is this a parameter that needs to be removed (and break compatibility), is the function implemented wrong and does it need to use ht in the copy...?

**Comment by ProfElements** [comment]
The parameter has been taken since this github's start, yet it wasnt used then either. So I was wondering why it still used?

**Comment by eku** [comment]
If you change the signature of the function you'll break compatibility.

**Comment by ProfElements** [comment]
Ohh so its just a compatibility thing. Thank you :bow:
