### ISSUE TITLE
GameCube: printf() does not work properly

### ISSUE THREAD

**Issue by mardy** [devkitPro/libogc#163]
### What's the issue you encountered?

`printf()` and `puts()` do not work properly.

### How can the issue be reproduced?

- Build any program for the GameCube, which uses `puts()` or `printf()`
- Run it with Dolphin emulator, with the debugger enabled

When building for the Wii, everything works as expected: you will see the messages you print in the logs. When building for the GameCube, `puts()` messages are not displayed at all, and `printf()` can have one of the following results:

1. Crash the application
2. Do not print anything (if the format string does not contain any `%`)
3. Print the second argument: for example, the statement `print("Hello, %s\n", name)` will print only the value of `name`, without "Hello, ".

### Environment?

- What host OS are you using?
  - Ubuntu 22.04 (dolphin as a flatpak)
  - Official release or unofficial/self-compiled build: 
    - devkitPPC r44.2-2

### Additional context?

- Does not happen when building for the Wii
- I don't have a modded GameCube, so I couldn't test it there
- It might very well be a Dolphin issue

**Comment by WinterMute** [comment]
I reproduced this earlier and I have no idea what's going on. There's something very wrong with the symbol overrides in Dolphin but I don't think that's something we can fix. I thought it was perhaps the recent move to dwarf5 debug info but that doesn't explain why wii code appears to work. This is definitely a Dolphin problem & not a devkitPPC/libogc problem.

I have, however, long been meaning to look at how Dolphin emulates OSReport messages and add libogc support for that. Your issue prompted me to look again & I committed https://github.com/devkitPro/libogc/commit/167ba589ba7501855cb0ae26df28f6909c0729ed and released libogc 2.5.0

You can now just enable OSReport EXI (OSREPORT) in the log configuration and either use SYS_Report directly with printf semantics - i.e. `SYS_Report("ze pointer is %p\r", ptr);` or use SYS_STDIO_Report to redirect stderr and optionally stdout so you can use fprintf/printf & family.
