### ISSUE TITLE
PAD_ScanPads() reports GameCube controller continuously connecting and disconnecting

### ISSUE THREAD

**Issue by mardy** [devkitPro/libogc#165]
## Bug Report

If my understanding is correct, the return value of `PAD_ScanPads()` is a bit mask where the less significant 4 bits are set to 1 if the respective controller is connected, and 0 otherwise.

Both in a real Wii and in Dolphin, if `PAD_ScanPads()` is called on every frame, a connected GameCube controller is reported as present on one call, and absent on the next one, and so on. In order to avoid reporting this wrong information to the application, I've introduced a workaround where I expect `PAD_ScanPads()` to return 0 for 4 times in a row before reporting that the joystick has been removed: https://github.com/mardy/SDL/blob/ogc-sdl2-2.28/src/joystick/gamecube/SDL_sysjoystick.c#L171-L188

My guess is that `PAD_Read()` returns a structure where the `err` member is set to `PAD_ERR_NOT_READY` or to `PAD_ERR_TRANSFER`, and `PAD_ScanPads()` then just returns the controller as not present. 

I think that overall the behaviour of `PAD_ScanPads()` is correct, but there should be a way for the client to read the error status. Would you be against adding a `s8 PAD_GetError(s32 chan)` function which returns the value of `__pad_keys[chan].err`? If not, I can prepare a pull request.

**Comment by DacoTaco** [comment]
did a quick look, and it looks like `PAD_ScanPads` only sets the connected flag if the pad's status is `PAD_ERR_NONE`
( https://github.com/devkitPro/libogc/blob/master/libogc/pad.c#L724 )

i'd need to test this, but if the pad is in the middle of a transfer, i can see that it wouldn't be marked as 'connected'.

this seems like a mismatch of the function docs saying it reports which controller is connected, but the function reports which controllers had input data ready to be processed.

**Comment by mardy** [comment]
> where did you read that it reports the connected pads @mardy ? asking because there are no doxygen docs for pad

Nowhere :-) I only looked at the code, and according to the logic and the name of the local variables, I assumed that the intent of the function was to return a bitmask of the connected pads.

**Comment by DacoTaco** [comment]
its more a bitmask of pads that are read to by the PAD_* functions

**Comment by WinterMute** [comment]
Yes. The variable is misnamed & we should probably add some documentation of these functions.

https://github.com/devkitPro/libogc/commit/736927300865773d9af33f12f2028d9aa4e3e4a0

**Comment by mardy** [comment]
OK. And what about the idea of adding PAD_GetError()? I guess that it could be used to detect if the pad is connected?
