### ISSUE TITLE
Impossible to link to libogc with devkitPPC r29+ and -Wl,--no-gc-sections

### ISSUE THREAD

**Issue by csnover** [devkitPro/libogc#17]
libogc [uses an extern for _wrapup_reent](https://github.com/devkitPro/libogc/blob/master/libogc/newlibc.c#L10).

In https://github.com/devkitPro/newlib/commit/99e87649c7c5840ad9f1304b2ceb06a02fd40b3a `_wrapup_reent` was removed. In https://github.com/devkitPro/buildscripts/commit/116ad3bfc444abfb9e0cf2594801ab03e96c70b8 a patch was added to restore this function, then that patch was deleted by https://github.com/devkitPro/buildscripts/commit/e48ba38ce5712b579eb7392ea407a1f5561275ad and not replaced. Therefore, even when using the official build scripts, it appears to now be impossible to link libogc when using devkitPPC r29 or later, since `_wrapup_reent` does not exist:

test.cpp:

```cpp
int main() { return 0; }
```

compiler error:

```
$ powerpc-eabi-g++ -L/opt/devkitpro/devkitPPC/lib -mogc -L/opt/devkitpro/libogc/lib/cube -logc -Wl,--no-gc-sections -isystem /opt/devkitpro/devkitPPC/include -I/opt/devkitpro/libogc/include ./test.cpp
/opt/devkitpro/libogc/lib/cube/libogc.a(newlibc.o): In function `__libc_wrapup':
C:/Users/davem_000/projects/devkitPro/libogc/libogc/newlibc.c:67: undefined reference to `_wrapup_reent'
collect2: error: ld returned 1 exit status
```

**Comment by csnover** [comment]
Sorry, the original report was a bit light on details. I have updated it with additional pertinent information. As far as “why --no-gc-sections”, I’ve inherited this code, and my understanding is that it is because it generates dynamically-loaded plugins and collecting “dead” code breaks them.

**Comment by WinterMute** [comment]
Should be fixed with https://github.com/devkitPro/libogc/commit/19559a9ec579e655049600145376f7134d1ff2d8

The patch to restore _wrapup_reent was removed because it wasn't necessary. Dead code elimination disguised the issue you're having (although it has to  be said, plugin style things **should** be possible with dead code elimination enabled)
