### ISSUE TITLE
asndlib 2.6.0 has no sound on dolphin (DSP HLE)

### ISSUE THREAD

**Issue by KittyPBoxx** [devkitPro/libogc#174]
## Bug Report

Compiling with asndlib 2.6.0 results in no audio on Dolphin with the default DSP HLE emulation. When compiling with asndlib 2.5.0 the audio works as expected.  

### What's the issue you encountered?

When updating from 2.5.0 to 2.6.0 audio stopped working in dolphin.  The console logs `Unknown ucode (CRC = 5dbf8bf1)`. I can't hear any issues using DSP LLE emulation or when testing on real hardware so this may purely be an emulation issue to report to dolphin. 

### How can the issue be reproduced?

Build a project using 2.6.0 that calls `ASND_Init();` and run in dolphin with the default settings. 

### Environment?

Dolphin 5.0-21264
GNU/Linux 6.6.30 x86_64

### Additional context?

I compiled a project using all 2.6.0 libraries except linking a prebuilt version of asndlib 2.5.0 and there was no issue. This should confirm the error is caused by a change in asndlib and not any of the other libraries.

**Comment by fincs** [comment]
Seems like you may be running an older version of Dolphin without this PR merged: https://github.com/dolphin-emu/dolphin/pull/12665

**Comment by WinterMute** [comment]
Latest Dolphin is 5.0-21460

**Comment by KittyPBoxx** [comment]
👍 I'll hold off updating till the newer dolphin is available for my distro
