### ISSUE TITLE
Remove heap allocation from netrecv_from

### ISSUE THREAD

**Issue by rafaelsamenezes** [devkitPro/libogc#177]
#### Overview:
- Remove the heap allocation from the [netrecv_from](https://github.com/devkitPro/libogc/blob/master/libogc/network_wii.c#L945C2-L945C32 ) method or expose a function that skips the allocation.

#### Smaller Details: 
- Alter the function so it does not need an extra allocation.
-  An alternative would be to expose a new function that avoids such allocation

#### Nature of Request:  
- Change

### Why would this feature be useful?

Projects that rely on arena allocators can take up the full mem2 space beforehand. This makes network request fail with no memory available even though the provided buffer could be used directly. I did not find any alternatives, please let me known if I am missing something.

For my use case, there is an issue of using retroachievements with retroarch: https://github.com/libretro/RetroArch/issues/16184#issuecomment-1951493281

In my tests, replacing the `netrecv_from` seems to fix the problem.

**Comment by DacoTaco** [comment]
euh, i think the correct fix here is that you don't write into the allocated heap of the network stack?
it allocates the stuff using [net_alloc](https://github.com/devkitPro/libogc/blob/master/libogc/network_wii.c#L277-L280) ( and free's it after) which is created when [init'ing network](https://github.com/devkitPro/libogc/blob/master/libogc/network_wii.c#L271)

how did you end up making that return a fail on allocation without using that specific heap?

**Comment by rafaelsamenezes** [comment]
> euh, i think the correct fix here is that you don't write into the allocated heap of the network stack?
> it allocates the stuff using [net_alloc](https://github.com/devkitPro/libogc/blob/master/libogc/network_wii.c#L277-L280) ( and free's it after) into the network heap, which is created when [init'ing network](https://github.com/devkitPro/libogc/blob/master/libogc/network_wii.c#L271)
> 
> how did you end up making that return a fail on allocation without using that specific heap?
> 

Ow, I see. Thanks for the explanation, i misunderstood how the implementation works.

> EDIT : we are also looking at how its possible you are hitting the limit. are your packets size > 64k ?

Yeah, I recorded some recv calls with 65544 of length. I also tried to split the request into multiple smaller requests, which helped in some cases. I will try again now that i know about the hard limit.

**Comment by DacoTaco** [comment]
the network heap is 64k in size, so ye if you request packets to be bigger than that it might bump into the error.

see how far you can get with that information, and let us know. there might be some things we can do to help the issue, but first see how far you can get in splitting it up! :)

**Comment by mardy** [comment]
Maybe you could add a `net_set_heap(void *heap, size_t size)` function to be called before initializing the network, that will set the heap to a client-supplied buffer.

**Comment by rafaelsamenezes** [comment]
Just an update, I tested replacing the direct net_recv calls with:

```c
static inline s32 recv_split(s32 s, void *mem, s32 len, u32 flags) {
  const s32 LIMIT = 48 * 1024;
  s32 max_tries = 1000;
  s32 res = 0;

  while(len) {
    s32 recv_length = len < LIMIT ? len : LIMIT;
    s32 recv_call_res = net_recv(s, mem, recv_length, flags);
 
    if (isagain(recv_call_res) && max_tries--)
      continue;    
    else if(recv_call_res < 0)
      return recv_call_res;
    
    mem = (char *)mem + recv_length;
    len -= recv_length;
    res += recv_call_res;
  }
  
  return res;
}
```

This seems to solve the allocation issue. Thanks for your support!

**Comment by DacoTaco** [comment]
@rafaelsamenezes : do you have any code i can test a libogc change with? im currently working on doing the netrecv_from in blocks, so the user code doesn't need to do it in blocks like you did :)

**Comment by DacoTaco** [comment]
that kinda sounds like a lot of setup haha.
do you mind building the libogc branch and testing it?
on my end it worked in priiloader

**Comment by DacoTaco** [comment]
@rafaelsamenezes : did you test it?

**Comment by DacoTaco** [comment]
closing due to no response, and because branch is merged
