### ISSUE TITLE
network_wii's if_config() does not populate netmask or gateway

### ISSUE THREAD

**Issue by emilydaemon** [devkitPro/libogc#179]
### What's the issue you encountered?

network_wii's if_config function does not populate netmask or gateway, even though these are accepted as parameters.
I expected them to be populated with subnet mask and default gateway respectively, but the function does not make any changes to them.

### How can the issue be reproduced?

1. Copy the template project folder.
2. Include the network.h header.
3. Call if_config() with three separate character arrays (each 16 characters long). The last two parameters should be set to `TRUE` and `20`.
4. Check the values of each array. The first one is populated as expected (ex. `192.168.68.52`), but the second and third arrays are left unchanged.

### Environment?

I am using Windows 10 with the supplied msys2 shell, but I do not believe that this is relevant to the problem.

**Comment by DacoTaco** [comment]
hey emily!

just took a quick look, and it seems to parameters are unused ( https://github.com/devkitPro/libogc/blob/master/libogc/network_wii.c#L60 ) ! question is though, are they retrieved in the ios calls...
ill have to dig deeper!

**Comment by DacoTaco** [comment]
found something in dolphin. IOS' /dev/net/ip/top device has a IOCTLV called GetInterfaceOption that can retrieve the ip, gateway and subnet mask. i think our GetHostIp call needs to be replaced with this.
source : https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/IOS/Network/IP/Top.cpp#L981-L991

**Comment by DacoTaco** [comment]
![image](https://github.com/user-attachments/assets/9f994506-d431-4ac7-a58d-8950a612d202)

got the call implemented. need to clean up my code and fix dolphin's implementation of the ioctlv :)

**Comment by DacoTaco** [comment]
@emilydaemon : this is now implemented in libogc! the next release will fetch and report them nicely now!
in dolphin its currently broken, but a pull request is also made there to have it fixed :)
https://github.com/dolphin-emu/dolphin/pull/13066
