### ISSUE TITLE
card.c: __card_allocblock() not being able to allocate last block

### ISSUE THREAD

**Issue by suloku** [devkitPro/libogc#4]
In line 791 of current commit of card.c, in __card_allocblock():

```
    if(count>=(card->blocks-CARD_SYSAREA)) return CARD_ERROR_BROKEN;
```

This will always be true for the last block of the memory card, thus not being able to write to it. The fix is simple:

```
    if(count>(card->blocks-CARD_SYSAREA)) return CARD_ERROR_BROKEN;
```

(This information was reported by undergroundmonorail, I saw it wasn't fixed in libog and I thought I'd tell)

UPDATE: after some testing the problem only happens in the following scenario: writing a 59 block file to a 59 block memory card.
There is no problem if card has 48 occupied blocks and then a 11 block file is written.
I made a 251 block file for testing purposes and the same behavior appears. I won't test 1024 or 2048 cards since the same behavior is expected.

Also, I found a bug in Card_delete, opening issue

**Comment by WinterMute** [comment]
sorry for leaving this so long, fix committed now
