### ISSUE TITLE
card.c: __card_freeblock() forgets to free one block on all files

### ISSUE THREAD

**Issue by suloku** [devkitPro/libogc#5]
If you take a look at this part of the function, you'll quickly notice that if the file is 1 block lenght, the block is never freed in the fat table

```
   //   ...
next = fatblock->fat[block-CARD_SYSAREA];
while(1) {
    if(next==0xffff) break;
    if(next<CARD_SYSAREA || next>=card->blocks) return CARD_ERROR_BROKEN;

    // Get the file's next block and clear the previous one from the fat
    prev = next;
    next = fatblock->fat[prev-CARD_SYSAREA];
    fatblock->fat[prev-CARD_SYSAREA] = 0;
    fatblock->freeblocks++;
}
return __card_updatefat(chn,fatblock,callback);
```

I tried the following fix, I've done some savegame writing and erasing and seems to work fine so far, there were no missing blocks and they were correctly allocated:

```
next = fatblock->fat[block-CARD_SYSAREA];
    /*+++/* fatblock->fat[block-CARD_SYSAREA] = 0;
    /*+++*/ fatblock->freeblocks++;
while(1) {
    if(next==0xffff) break;
    if(next<CARD_SYSAREA || next>=card->blocks) return CARD_ERROR_BROKEN;

    // Get the file's next block and clear the previous one from the fat
    prev = next;
    next = fatblock->fat[prev-CARD_SYSAREA];
    fatblock->fat[prev-CARD_SYSAREA] = 0;
    fatblock->freeblocks++;
}
return __card_updatefat(chn,fatblock,callback);
```

I'm not really sure if this is the correct way to fix the problem, if someone can confirm or update card.c with a better method I'll be thankful!

**Comment by Antidote** [comment]
I actually had to implement exactly this just a few days ago and it works exactly as you expect, I just need to port it to libogc, I'll give it a shot here when I'm not too busy.

**Comment by WinterMute** [comment]
committed your fix for this too.
