### ISSUE TITLE
POLLOUT seems to be wrong

### ISSUE THREAD

**Issue by Midar** [devkitPro/libogc#55]
It seems that POLLOUT is wrong. When I use it, I don't ever get any events. However, when I used 0x8 (what POLLERR is currently defined to), it works. I'm suspecting those two are swapped?

**Comment by mtheall** [comment]
When you say "it works" do you mean you can begin writing to the socket and the peer receives that data?

**Comment by Midar** [comment]
Almost: There's currently no net_getsockopt, so I cannot check for errors. But the write event is triggered and if I just pretend that there was no error, I can send a HTTP request and get an answer back.

**Comment by mtheall** [comment]
"the write event is triggered" you mean you start getting POLLERR in revents?

**Comment by Midar** [comment]
I undef POLLOUT and define it to 8. If I do this, I get POLLOUT events as soon as the connection is established or failed.

**Comment by endrift** [comment]
This was fixed in 5747c7477901d7f8d62c323ea24b539adc0bf777.
