### ISSUE TITLE
net_getsockopt is missing while net_setsockopt is there

### ISSUE THREAD

**Issue by Midar** [devkitPro/libogc#56]
It's possible to set socket options, but it's not possible to get them.

In particular, it would be nice to get net_getsockopt working with SOL_SOCKET, SO_ERROR, as that would make it possible to get the error status of an async connect().

**Comment by DacoTaco** [comment]
this has been implemented in https://github.com/devkitPro/libogc/commit/f43c8183b0cd7d62e6f844ab25caeea188c1028b
