### ISSUE TITLE
libtinysmb is a piece of shit

### ISSUE THREAD

**Issue by tueidj** [devkitPro/libogc#63]
Steps to reproduce:
1. Mount a remote share with write access (using smbInit or smbInitDevice).
2. open() an existing non-zero length file on the share with flags=O_RDWR (equivalent to fopen(foo, "r+")). For maximum effect choose a savegame file that contains many hours of progress.
3. Observe the file no longer contains any data and has been truncated to zero bytes.
4. Realize libtinysmb is a piece of shit.

**Comment by DacoTaco** [comment]
fixed in main (thanks extrems)
