### ISSUE TITLE
Wrong 480p configuration settings

### ISSUE THREAD

**Issue by gingerbeardman** [devkitPro/libogc#64]
unwanted links removed, sorry.

**Comment by WinterMute** [comment]
Sorry @gingerbeardman you've linked to a hostile libogc fork, please don't.

If you require changes that can be tested to be compatible with official devkitPPC/libogc then please feel free to submit a PR.

**Comment by gingerbeardman** [comment]
Hi. I wasn't aware of the fork relationship. Sorry

I'll file a PR soon.

**Comment by gingerbeardman** [comment]
I see a PR has been filed (not by me!)
