### ISSUE TITLE
undefined reference to `__locale_ctype_ptr'

### ISSUE THREAD

**Issue by Klairm** [devkitPro/libogc#69]
When trying to build a program i have the following error: 
> status
make
linking ... Wii.elf
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libSDL.a(SDL_string.o): in function `SDL_strlwr':
C:\Users\Daryl\git\sdl-wii\SDL/src/stdlib/SDL_string.c:398: undefined reference to `__locale_ctype_ptr'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: C:\Users\Daryl\git\sdl-wii\SDL/src/stdlib/SDL_string.c:398: undefined reference to `__locale_ctype_ptr'
collect2: error: ld returned 1 exit 
>

this is how my Makefile looks like:

https://pastebin.com/H0Ju55uJ

**Comment by endrift** [comment]
Make sure your devkitPPC and SDL installation is up to date. This isn't a libogc bug.

**Comment by fincs** [comment]
I.e. `pacman -Syu`

**Comment by Klairm** [comment]
SDL has to be the wii SDL , right? cuz it's up to date

**Comment by WinterMute** [comment]
we don't currently supply SDL and would prefer it be built and packaged properly. It will need rebuilt with latest tools.
